# @package _global_

rewards:
  stand_still_dof_vel_l2:
    weight: -0.1
    params:
      asset_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: robot
        joint_names: [".*"]
      command_name: base_velocity

  feet_contact_without_cmd:
    weight: 1.0
    params:
      command_name: base_velocity
      sensor_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: contact_forces
        body_names:
          - ".*ankle_roll.*"

  track_stand_still_exp:
    weight: 3.0
    params:
      command_name: base_velocity
      std: 0.5

  track_lin_vel_xy_heading_aligned_frame_exp:
    weight: 3.0
    params:
      std: 0.5
      command_name: base_velocity

  track_ang_vel_z_heading_aligned_frame_exp:
    weight: 3.0
    params:
      std: 0.5
      command_name: base_velocity

  is_alive:
    weight: 0.5
    params: {}

  lin_vel_z_l2:
    weight: -1.0
    params: {}

  ang_vel_xy_l2:
    weight: -5.0e-2
    params: {}

  joint_acc_l2:
    weight: -2.5e-7
    params: {}

  action_rate_l2:
    weight: -1.0e-2
    params: {}

  joint_pos_limits:
    weight: -5.0
    params:
      asset_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: robot
        joint_names: [".*"]

  energy:
    weight: -1.0e-3
    params: {}

  feet_air_time:
    weight: 0.15
    params:
      threshold: 0.4
      sensor_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: contact_forces
        body_names: [".*ankle_roll.*"]
      command_name: base_velocity

  fly:
    weight: -1.0
    params:
      threshold: 1.0
      sensor_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: contact_forces
        body_names: [".*ankle_roll.*"]

  feet_too_near:
    weight: -2.0
    threshold: 0.20
    params:
      asset_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: robot
        joint_names:
          - .*ankle_roll.*

  joint_deviation_l1_arms:
    weight: -0.4
    params:
      asset_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: robot
        joint_names:
          - .*waist.*
          - .*_shoulder_roll.*
          - .*_shoulder_yaw.*
          - .*_wrist.*

  joint_deviation_l1_legs_yaw:
    weight: -0.15
    params:
      asset_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: robot
        joint_names:
          - .*_hip_yaw.*
          - .*_hip_roll.*
          - .*_shoulder_pitch.*
          - .*_elbow.*

  joint_deviation_l1_legs:
    weight: -0.02
    params:
      asset_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: robot
        joint_names:
          - .*_hip_pitch.*
          - .*_knee.*
          - .*_ankle.*

  flat_orientation_l2:
    weight: -1.0
    params: {}

  base_height_l2:
    weight: -10.0
    params:
      target_height: 0.785

  feet_slide:
    weight: -0.25
    params:
      asset_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: robot
        body_names: [".*ankle_roll.*"]
      sensor_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: contact_forces
        body_names: [".*ankle_roll.*"]

  undesired_contacts:
    weight: -1.0
    params:
      threshold: 1.0
      sensor_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: contact_forces
        body_names:
          - ${robot.undesired_contacts_regrex}

  torso_xy_ang_vel_l2_penalty:
    weight: -1.0
    params: {}

  torso_upright_l2_penalty:
    weight: -5.0
    params: {}

  torso_linacc_xy_l2_penalty:
    weight: -0.1
    params: {}
