# @package _global_

obs:
  context_length: 8
  n_fut_frames: 8
  target_fps: 50
  # Select which motion source to use in observations: "", "ref_", "ft_ref_", "robot_"
  actor_obs_prefix: "ref_"
  critic_obs_prefix: "ref_"

  obs_groups:
    policy:
      atomic_obs_list:
        - ref_dof_pos_fut:
            params:
              ref_prefix: ${obs.actor_obs_prefix}
            noise:
              type: AdditiveUniformNoiseCfg
              params:
                n_min: -0.05
                n_max: 0.05

        - ref_dof_pos_cur:
            history_length: ${obs.context_length}
            flatten_history_dim: true
            params:
              ref_prefix: ${obs.actor_obs_prefix}
            noise:
              type: AdditiveUniformNoiseCfg
              params:
                n_min: -0.05
                n_max: 0.05

        - projected_gravity:
            history_length: ${obs.context_length}
            flatten_history_dim: true
            noise:
              type: AdditiveUniformNoiseCfg
              params:
                n_min: -0.1
                n_max: 0.1

        - rel_robot_root_ang_vel:
            history_length: ${obs.context_length}
            flatten_history_dim: true
            noise:
              type: AdditiveUniformNoiseCfg
              params:
                n_min: -0.2
                n_max: 0.2

        - dof_pos:
            history_length: ${obs.context_length}
            flatten_history_dim: true
            noise:
              type: AdditiveUniformNoiseCfg
              params:
                n_min: -0.01
                n_max: 0.01

        - dof_vel:
            history_length: ${obs.context_length}
            flatten_history_dim: true
            noise:
              type: AdditiveUniformNoiseCfg
              params:
                n_min: -0.5
                n_max: 0.5

        - last_action:
            history_length: ${obs.context_length}
            flatten_history_dim: true

      enable_corruption: true
      concatenate_terms: true

    critic:
      atomic_obs_list:
        - ref_dof_pos_cur:
            params:
              ref_prefix: ${obs.critic_obs_prefix}
        - ref_dof_pos_fut:
            params:
              ref_prefix: ${obs.critic_obs_prefix}
        - global_anchor_diff:
            params:
              ref_prefix: ${obs.critic_obs_prefix}
        - rel_robot_root_lin_vel: {}
        - rel_robot_root_ang_vel: {}
        - global_robot_bodylink_lin_vel_flat: {}
        - global_robot_bodylink_ang_vel_flat: {}
        - root_rel_robot_bodylink_pos_flat: {}
        - root_rel_robot_bodylink_rot_mat_flat: {}
        - dof_pos: {}
        - dof_vel: {}
        - last_action: {}
      enable_corruption: false
      concatenate_terms: true
