# @package _global_

defaults:
  - /training: train_base
  - /algo: ppo
  - /robot: unitree/G1/29dof/29dof_training_isaaclab
  - /env: motion_tracking
  - /env/terminations: termination_motion_tracking
  - /env/observations: motion_tracking/obs_motion_tracking
  - /env/rewards: motion_tracking/rew_motion_tracking
  - /env/domain_randomization: domain_rand_small
  - /env/terrain: isaaclab_rough_lite
  - /modules: motion_tracking/mlp_motrack_unitree_g1

project_name: HoloMotionMotionTracking

robot:
  motion:
    train_hdf5_roots:
      - data/hdf5_datasets/processed_datasets/h5_AMASS_test

algo:
  config:
    save_interval: 500
    dynamo_backend: "inductor"

    module_dict:
      actor: ${modules.actor}
      critic: ${modules.critic}
